version: '3'
services:
  thenarratedpuritan:
    container_name: thenarratedpuritan
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASS=${EMAIL_PASS}
      - TEMP_POST_PASS=${TEMP_POST_PASS}
      - SUBS_EMAIL=${SUBS_EMAIL}
    restart: always
    build: .
    ports:
      - '3000:3000'
    restart: always
#     volumes: ['./:/var/www/html']
    environment:
      VIRTUAL_HOST: web.thenarratedpuritan.com, www.web.thenarratedpuritan.com
      LETSENCRYPT_HOST: web.thenarratedpuritan.com, www.web.thenarratedpuritan.com
      LETSENCRYPT_EMAIL: thenarratedpuritan@gmail.com
networks:
  default:
    external:
      name: nginx-proxy